### ISSUE TITLE
Automate day before email

### ISSUE THREAD

**Issue by bkellgren** [CoderDojoChi/coderdojochi#466]

**Comment by karbassi** [comment]
The day before the class (`session`), there are emails that are currently manually sent out by me (@karbassi). We'd like to move this into the Django system to be automated.

## Tasks

- [ ] There is a 48-hour before class email currently in the code base. Rename or remove it.
- [ ] Create an email to be sent out at **3pm CST** the day before the event. For example, if there is a class (event) happening on Saturday at 10am, these emails should be sent out on Friday at 3pm.
- [ ] Make sure all emails are sent on the CST timezone.
- [ ] There is one email template for mentors and one for guardians.
- [ ] Make sure each email has an HTML and TEXT version.

## Template Text

### Mentors
#### Subject
> <MENTOR_FIRST_NAME>, a few notes about tomorrows CoderDojoChi class

#### Body
> Hello <MENTOR_FIRST_NAME>,
> 
> I wanted to send you a few notes about tomorrow's class.
> 
>  - The class location is at **<SESSION LOCATION>**.
> 
>  - **Please be there by <SESSION MENTOR START TIME>**. We will need to set up this space and we will need everyone's help. Class ends at <SESSION END TIME>, we break down and are out by <SESSION MENTOR END TIME>. If you need to leave by <SESSION END TIME>, please reach out to me and we can make it work!
> 
>  - **Parking may be difficult**, but [we've partnered with SpotHero to find you parking](https://spothero.com/search?latitude=41.8762291&longitude=-87.6532041&zoom=15). For new users, enter promo code **CODERDOJOCHI** and get $10 off at checkout.
>
> - We can't thank <SESSION LOCATION NAME> enough for being our partner and host. Let's show them what how awesome CoderDojoChi is!
> 
> - Be ready to have a blast!
> 
> See you tomorrow!
> 


### Guardian
#### Subject
> <GUARDIAN_FIRST_NAME>, CoderDojoChi Class is tomorrow!

#### Body

> Hello <GUARDIAN_FIRST_NAME>,
>
> I wanted to send you a few notes about tomorrow's class.
>
> - The class it at **<SESSION LOCATION>**.
> 
> - **Class starts promptly at <SESSION START TIME>**. Please plan on arriving by <SESSION START TIME minus 15 minutes> to give time for check-in and seating. The class will be let out at <SESSION END TIME>.
> 
> - **Parking may be difficult, but [we've partnered with SpotHero to find you parking](https://spothero.com/search?latitude=41.8762291&longitude=-87.6532041&zoom=15).** For new users, use the code **CODERDOJOCHI** at checkout. This will give you $10 off at checkout.
> 
> - This is a full class, **please notify us tonight if you cannot make it.** We'd love to have you there!
>
> - **All equipment is provided.** Just bring a hungry mind!
>
> - Speaking of hungry, **food will be provided for free**. Normally we serve pizza as it is a crowd-pleaser. *If your children have any dietary restrictions, please pack a lunch.* We like to surprise the kids, so don't spill the beans about the pizza!
> 
> - As noted on the site, **we'd love to have all the parents participate during the class**. We ask all parents attending the first time to stay and observe the class. Don't worry if you don't know anything about the course. That's why we're teaching it! However, we do understand that some parents have to be at work during class time.
> 
> - **This class is provided to you for free**, however, we do ask for a donation if you enjoyed the class. We've been asked to give parents a heads up about bringing cash or their credit cards.
> 
> - We can't thank <LOCATION NAME> for being our host. Let's show them what Chicago youth can do!
> 
> - Be ready to have a blast!
>
> See you tomorrow!
>
> Thank you,
>
> <SESSION TEACHER NAME>
>

**Comment by karbassi** [comment]
This is a more complete issue, but it is a duplicate of #394.

**Comment by chijoy** [comment]
# Steps to find the orders that are active, and day reminders haven't been sent (false) and are less than a week away more than a day
1. Find Orders
1. Limit orders by is_active = True
1. Limit orders by day_reminder_sent=False
1. Define variable for tomorrow = timezone.now() + datetime.timedelta(days=1)
1. Define variable for week = timezone.now() + datetime.timedelta(days=7)
1. Write a for loop to go through each order array in those filtered orders to print out the order session start date that fall within the tomorrow and week variables
1. send the updated txt and html email
1. update day_reminder_sent=True
